### ISSUE TITLE
Peer to Peer review

### ISSUE THREAD

**Issue by pasytchangwa** [sheylaPozo/todolist#1]
Hello @sheylaPozo , congratulations. you have done a great job so far 👏 but you could improve your code by adding an 'enter' button next to your input tag as required by the original version. 
![image](https://user-images.githubusercontent.com/64914462/126605382-ab6dcf73-a935-4b3c-b933-7bfcf6726eb5.png)

**Comment by sheylaPozo** [comment]
> Thank you for the suggestions and the help :3  🥇
